version: '3'

services:

  node_api:
    build: .
    environment:
      - ENV_IN=docker
    ports:
      - "1338:1338"
    volumes:
      - ./logs:/app/logs
    networks:
      - db
    command: npm run start
    restart: always
    depends_on:
      - mongo


  mongo:
    image: mongo:3.4.4
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - db
    restart: always

networks:
  db:
    driver: bridge
